name: Hello World
#When to trigger this pipeline. We can push or normal or someother events like creating PR, Updating PR, Creating branches, creating issues
on: [push] #triggers
jobs: #Pipelines i.e., one workflows can have multiple pipelines
  hello: 
    runs-on: ubuntu-latest #it indicates destination platform to be run similar to agent in jenkins
    steps: # stages
      - name: step1
        run: echo "Hello World"
      - name: step2
        run: echo "Hello Github Actions"
        
