name: Inputs
on:
  workflow_dispatch: #Giving Inputs at run time and Trigger manually 
    inputs:
      loglevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test Scenatio tag learning'
        required: true
        type: string
      environment: 
        description: 'environment to run tests against' # Implementation platform
        required: true
        type: environment
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag STDOUT
        run: echo The tags are ${{ inputs.tags }}
      - name: Print the environment
        run: echo The tags are ${{ inputs.environment }}
