name: Dependency
on: [push] # triggers
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hi, This is from job 1"

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - name: Step2
        run: echo "Hi, This is from job 2"
  
  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: Step3
        run: echo "Hi, This is from job 3"

  job-4:
    runs-on: ubuntu-latest
    steps:
      - name: Step4
        run: echo "Hi, This is from job 4"