name: Checkout
on: #[push]
  push:
    paths:
      - '.github/workflows/06-checkoutactions.yaml'
jobs: 
  build: #Stages
    runs-on: ubuntu-latest
    steps:
      #Checkout will happen here
      - name: checkout
        uses: actions/checkout@v5

      - name: display the files
        run: ls -la
        
