name: Checkout
on:
  push:
    paths:
      - '.github/workflows/06-checkoutactions.yaml'
jobs:
  build: # Refers Job name
    runs-on: ubuntu-latest
    steps: # Refer Stages 
      #Checkout will happen here in first step and second step in another steps
      - name: checkout
        uses: actions/checkout@v5

      - name: Display the files
        run: ls -la
